#steps:
#- name: 'gcr.io/cloud-builders/gcloud'
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#  entrypoint: 'bash'
#  args: ['-c', 'mkdir -p ./creds']
#  args: ['-c', 'echo ${{ secrets.SERVICEACCOUNT_bigquery }} > ./creds/serviceaccount.json']
#  args: ['-c', 'gcloud auth activate-service-account --key-file serviceaccount.json']
#  args: ['-c', 'bq --project_id=burnished-case-280710 query --nouse_legacy_sql < my_query.sql']
#  args: ['run_query.sh', 'my_query.sql']
steps:
  - name: gcr.io/community-builders/bq
    args:
    - query
    - --nouse_legacy_sql
    - < my_query.sql

